spring:
  config:
    activate:
      on-profile: test
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

server:
  port: 0

logging:
  level:
    root: WARN
    com.docvault: DEBUG
